# Generated by Django 5.0.6 on 2024-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='descricao',
            field=models.CharField(default='CLT', max_length=60, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=120, null=True),
        ),
    ]
