# Generated by Django 5.0.6 on 2024-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_contrato_descricao_contrato_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'verbose_name': 'Hora Jornada', 'verbose_name_plural': 'Horas Jornadas'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Jornada'),
        ),
    ]
