# Generated by Django 5.0.6 on 2024-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_alter_contrato_options_alter_jornada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
