# Generated by Django 5.0.6 on 2024-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem'),
            preserve_default=False,
        ),
    ]
