# Generated by Django 5.0.6 on 2024-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_alter_jornada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
