# Generated by Django 5.0.6 on 2024-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('det', 'Tempo Determinado'), ('ind', 'Tempo Indeterminado'), ('evn', 'Eventual'), ('est', 'Estágio'), ('exp', 'Experiência'), ('tel', 'Teletrabalho'), ('int', 'Intermitente'), ('pj', 'Autônomo')], default='ind', max_length=3, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descrição da Jornada'),
        ),
    ]
