# Generated by Django 5.0.6 on 2025-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0010_contrato_tipo_alter_contrato_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('det', 'Tempo Determinado'), ('ind', 'Tempo Indeterminado'), ('evn', 'Eventual'), ('est', 'Estágio'), ('exp', 'Experiência'), ('tel', 'Teletrabalho'), ('int', 'Intermitente'), ('pj', 'Autônomo'), ('soc', 'Sócio e Diretoria')], default='ind', max_length=3, verbose_name='Tipo de Contrato'),
        ),
    ]
