# Generated by Django 5.0.6 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0011_alter_contrato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variavel',
            name='valor',
            field=models.CharField(help_text='Como uma variável Python. Por exemplo, se boolean igual à True ou False.', max_length=512, verbose_name='Valor'),
        ),
    ]
