# Generated by Django 5.0.6 on 2024-07-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_curso_time'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='time',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
