# Generated by Django 5.0.6 on 2024-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_time_rename_expedicao_funcionario_data_expedicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='time',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Rescisão'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
