# Generated by Django 5.0.6 on 2024-07-05 19:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_remove_perfil_time_funcionario_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='resp_contato_sec',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Responsável Contato Secundário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacoes',
            field=django_ckeditor_5.fields.CKEditor5Field(default='teste', verbose_name='Observacoe'),
            preserve_default=False,
        ),
    ]
