# Generated by Django 5.0.6 on 2024-07-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_jornada_ordem'),
        ('funcionarios', '0008_jornadafuncionario_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadafuncionario',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.contrato', verbose_name='Contrato'),
        ),
    ]
