# Generated by Django 5.0.6 on 2024-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_alter_jornadafuncionario_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadafuncionario',
            name='ordem',
            field=models.IntegerField(editable=False, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='jornadafuncionario',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], editable=False, max_length=1, verbose_name='Tipo'),
        ),
    ]
