# Generated by Django 5.0.6 on 2024-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_jornadafuncionario_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='modelo',
            field=models.CharField(choices=[('PCC', 'Parar / Continuar / Começar'), ('SCI', 'Situação, Comportamento ou Impacto'), ('CNV', 'Comunicação Não Violenta')], max_length=100),
        ),
    ]
