# Generated by Django 5.0.6 on 2024-07-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_alter_jornada_ordem_alter_jornada_tipo'),
        ('funcionarios', '0011_alter_feedback_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rua',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Rua'),
        ),
        migrations.CreateModel(
            name='HistoricoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.FloatField(blank=True, null=True, verbose_name='Salário')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.cargo', verbose_name='Cargo')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.contrato', verbose_name='Contrato')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Histórico Funcionário',
                'verbose_name_plural': 'Histórico Funcionários',
            },
        ),
    ]
