# Generated by Django 5.0.6 on 2024-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0015_cargo_slug_setor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipo',
            field=models.CharField(max_length=120, verbose_name='Tipo de Documento'),
        ),
    ]
