# Generated by Django 5.0.6 on 2024-09-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0017_historicofuncionario_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicofuncionario',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
