# Generated by Django 5.0.6 on 2024-09-10 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0018_rename_observacoes_historicofuncionario_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicofuncionario',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='historicofuncionario',
            name='data_alteracao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Alteração'),
            preserve_default=False,
        ),
    ]
