# Generated by Django 5.0.6 on 2024-09-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0019_remove_historicofuncionario_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Conta Bancária'),
        ),
    ]
