# Generated by Django 5.0.6 on 2024-10-14 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0020_alter_funcionario_conta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadafuncionario',
            name='final_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Final da Vigência'),
        ),
        migrations.AddField(
            model_name='jornadafuncionario',
            name='inicio_vigencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início da Vigência'),
            preserve_default=False,
        ),
    ]
