# Generated by Django 5.0.6 on 2024-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0021_jornadafuncionario_final_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadafuncionario',
            name='agrupador',
            field=models.IntegerField(default=1, editable=False, verbose_name='Agrupador'),
            preserve_default=False,
        ),
    ]
