# Generated by Django 5.0.6 on 2024-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0022_jornadafuncionario_agrupador'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_inicio_ferias',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Férias'),
        ),
    ]
