# Generated by Django 5.0.6 on 2024-11-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0023_funcionario_data_inicio_ferias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='visibilidade',
            field=models.CharField(choices=[('GERAL', 'Visibilidade Geral'), ('FINA', 'Apenas Financeiro'), ('ADMIN', 'Apenas acesso Admin'), ('OCULTO', 'Oculto')], default='GERAL', max_length=6),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='modelo',
            field=models.CharField(choices=[('PCC', 'Parar / Continuar / Começar'), ('SCI', 'Situação, Comportamento ou Impacto'), ('CNV', 'Comunicação Não Violenta'), ('GRL', 'Geral')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=16, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
