# Generated by Django 5.0.6 on 2024-11-13 16:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0024_funcionario_visivel_tipodocumento_visibilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacoes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Observacoes'),
        ),
    ]
