# Generated by Django 5.0.6 on 2024-11-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0025_alter_funcionario_conta_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início Período')),
                ('final', models.DateField(verbose_name='Final Período')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Estabilidade Funcionário',
                'verbose_name_plural': 'Estabilidade Funcionários',
            },
        ),
    ]
