# Generated by Django 5.0.6 on 2025-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0026_estabilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
