# Generated by Django 5.0.6 on 2025-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0027_remove_documento_documento_documento_lido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Pontuação de Assiduidade', 'verbose_name_plural': 'Pontuações de Assiduidade'},
        ),
        migrations.RemoveField(
            model_name='score',
            name='anomes',
        ),
        migrations.RemoveField(
            model_name='score',
            name='fechado',
        ),
        migrations.AlterField(
            model_name='score',
            name='pontuacao',
            field=models.FloatField(default=0, verbose_name='Pontuação'),
        ),
    ]
