# Generated by Django 5.0.6 on 2025-06-02 19:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('funcionarios', '0028_alter_score_options_remove_score_anomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Ausente'), (3, 'Ocupado')], default=1),
        ),
        migrations.AddField(
            model_name='setor',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_setor_set', to='funcionarios.funcionario', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conta_banco',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Contratação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro (a)'), ('C', 'Casado (a)'), ('D', 'Divorciado (a)'), ('V', 'Viúvo (a)'), ('U', 'União Estável')], default='S', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacoes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipo',
            field=models.CharField(max_length=120, verbose_name='Tipo de Documento'),
        ),
    ]
