# Generated by Django 5.0.6 on 2024-07-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='funcionarios',
            field=models.ManyToManyField(to='funcionarios.funcionario', verbose_name='Funcionáro'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.atividade', verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='solicitacaoferias',
            name='aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_aprovador', to='funcionarios.funcionario', verbose_name='Aprovador'),
        ),
        migrations.AddField(
            model_name='solicitacaoferias',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='documentosferias',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.solicitacaoferias', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.tipoatividade', verbose_name='Tipo'),
        ),
    ]
