# Generated by Django 5.0.6 on 2024-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='abono',
            field=models.IntegerField(default=0, verbose_name='Total Abono'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='final',
            field=models.DateField(verbose_name='Retorno'),
        ),
        migrations.AlterField(
            model_name='solicitacaoferias',
            name='abono',
            field=models.IntegerField(default=0, verbose_name='Total Abono'),
        ),
    ]
