# Generated by Django 5.0.6 on 2024-07-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_ferias_abono_alter_ferias_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='recorrencia',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.atividade', verbose_name='Recorrencia'),
        ),
    ]
