# Generated by Django 5.0.6 on 2024-08-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_atividade_recorrencia'),
        ('funcionarios', '0016_alter_tipodocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='autor',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='autor_atividade', to='funcionarios.funcionario', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
