# Generated by Django 5.0.6 on 2024-10-10 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_atividade_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='final',
            new_name='retorno',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='inicio',
        ),
        migrations.AddField(
            model_name='ferias',
            name='entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Entrada'),
            preserve_default=False,
        ),
    ]
