# Generated by Django 5.0.6 on 2024-10-10 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_rename_final_ferias_retorno_remove_ferias_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='final_periodo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Final Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferias',
            name='inicio_periodo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início Período'),
            preserve_default=False,
        ),
    ]
