# Generated by Django 5.0.6 on 2024-10-10 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_ferias_final_periodo_ferias_inicio_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='retorno',
        ),
        migrations.AddField(
            model_name='ferias',
            name='ano_referencia',
            field=models.IntegerField(default=0, verbose_name='Ano de Referência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferias',
            name='final_ferias',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Final Férias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferias',
            name='inicio_ferias',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início Férias'),
            preserve_default=False,
        ),
    ]
