# Generated by Django 5.0.6 on 2024-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_remove_solicitacaoferias_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='saldo',
            field=models.IntegerField(default=30, verbose_name='Saldo do Período'),
            preserve_default=False,
        ),
    ]
