# Generated by Django 5.0.6 on 2024-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_ferias_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoferias',
            name='status',
            field=models.IntegerField(choices=[(4, 'Em Análise'), (3, 'Pendente'), (2, 'Recusado'), (1, 'Aprovado'), (0, 'Aberto')], default=0, verbose_name='Status'),
        ),
    ]
