# Generated by Django 5.0.6 on 2025-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0027_remove_documento_documento_documento_lido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Sala')),
                ('tipo', models.CharField(choices=[('G', 'Grupo'), ('C', 'Conversa Privada')], default='C', max_length=1, verbose_name='Tipo de Sala')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionarios', models.ManyToManyField(blank=True, related_name='salas', to='funcionarios.funcionario', verbose_name='Funcionários')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_remetente', to='funcionarios.funcionario', verbose_name='Rementente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_sala', to='chat.sala', verbose_name='Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chat/', verbose_name='Arquivo')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_rementente', to='funcionarios.funcionario', verbose_name='Remetente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_sala', to='chat.sala', verbose_name='Sala')),
            ],
        ),
    ]
