# Generated by Django 5.0.6 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AddField(
            model_name='arquivo',
            name='nome_respondido',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Respondido do Usuário'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='text_respondido',
            field=models.TextField(blank=True, null=True, verbose_name='Respondido do Texto'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='nome_respondido',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Respondido do Usuário'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='text_respondido',
            field=models.TextField(blank=True, null=True, verbose_name='Respondido do Texto'),
        ),
        migrations.AddField(
            model_name='sala',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
    ]
