# Generated by Django 5.0.6 on 2024-08-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_remove_score_status_score_anomes_score_fechado_and_more'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0, verbose_name='Pontuação')),
                ('fechado', models.BooleanField(default=False, verbose_name='Fechado')),
                ('anomes', models.PositiveIntegerField(editable=False, verbose_name='Referência Ano Mês')),
                ('data_cadastro', models.DateTimeField(auto_now=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'unique_together': {('funcionario', 'anomes', 'fechado')},
            },
        ),
    ]
