# Generated by Django 5.0.6 on 2025-01-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_moeda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sugestao',
        ),
    ]
