# Generated by Django 5.0.6 on 2025-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_sugestao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moeda',
            options={'verbose_name': 'Histórico de Moeda', 'verbose_name_plural': 'Histórico de Moedas'},
        ),
        migrations.AlterUniqueTogether(
            name='moeda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moeda',
            name='motivo',
            field=models.CharField(max_length=120, null=True, verbose_name='Motivo'),
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='anomes',
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='fechado',
        ),
    ]
