# Generated by Django 5.0.6 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_moeda_options_alter_moeda_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humor',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='humor',
            field=models.CharField(choices=[('1', 'Estressante'), ('2', 'Sobrecarregado'), ('3', 'Equilibrado'), ('4', 'Tranquilo'), ('5', 'Produtivo')], max_length=1, verbose_name='Humor'),
        ),
    ]
