# Generated by Django 5.0.6 on 2025-03-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_alter_resposta_observacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaavaliacao',
            options={'verbose_name': 'Pergunta por Avaliação', 'verbose_name_plural': 'Perguntas por Avaliação'},
        ),
    ]
