# Generated by Django 5.0.6 on 2024-07-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='times', to='funcionarios.time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='curso',
            field=models.ManyToManyField(related_name='etapas', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='progressoetapa',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.etapa', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='progressoetapa',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
