# Generated by Django 5.0.6 on 2024-07-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='time',
        ),
    ]
