# Generated by Django 5.0.6 on 2024-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_alter_jornada_ordem_alter_jornada_tipo'),
        ('cursos', '0003_remove_curso_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='contrato',
        ),
        migrations.AddField(
            model_name='curso',
            name='contrato',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='configuracoes.contrato', verbose_name='Contrato'),
        ),
    ]
