# Generated by Django 5.0.6 on 2025-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_contrato_curso_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursofuncionario',
            options={'verbose_name': 'Curso por Funcionário', 'verbose_name_plural': 'Cursos por Funcionário'},
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado',
            field=models.BooleanField(default=False, verbose_name='Gerar Certificado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Certificado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('NDA', 'Nenhum'), ('CONC', 'Conclusão'), ('PART', 'Participação')], default='NDA', max_length=4, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='data_conclusao',
            field=models.DateTimeField(null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='uuid',
            field=models.CharField(default='417c09faaf484c69bf0f068696518f98', max_length=255, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
