# Generated by Django 5.0.6 on 2024-07-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionarios', models.ManyToManyField(related_name='funcionarios_feriados', to='funcionarios.funcionario', verbose_name='Funcionários')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('alterado', models.BooleanField(default=False, verbose_name='Alterado')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('encerrado', models.BooleanField(default=False, verbose_name='Encerrado')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Encerrado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Ponto de Horas',
                'verbose_name_plural': 'Ponto de Horas',
            },
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DurationField(help_text='Formato: DD hh:mm:ss', verbose_name='Saldo')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Data Inicial')),
                ('final', models.DateTimeField(verbose_name='Data Final')),
                ('tipo', models.CharField(choices=[('AT', 'Atestado'), ('AJ', 'Ausência Justificada')], max_length=2, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('documento', models.BinaryField(blank=True, null=True, verbose_name='Documento')),
                ('caminho', models.CharField(blank=True, max_length=256, null=True, verbose_name='Caminho do Documento')),
                ('status', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abono_aprovador', to='funcionarios.funcionario', verbose_name='Aprovador')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abono_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Solicitações de Abono',
                'verbose_name_plural': 'Solicitação de Abono',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('status', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_aprovador', to='funcionarios.funcionario', verbose_name='Aprovador')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Solicitações de Ajuste',
                'verbose_name_plural': 'Solicitação de Ajuste',
            },
        ),
    ]
