# Generated by Django 5.0.6 on 2024-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoabono',
            name='tipo',
            field=models.CharField(choices=[('AT', 'Atestado'), ('AJ', 'Ausência Justificada'), ('DC', 'Declaração'), ('FT', 'Falta')], max_length=2, verbose_name='Tipo'),
        ),
    ]
