# Generated by Django 5.0.6 on 2024-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_solicitacaoabono_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
