# Generated by Django 5.0.6 on 2025-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0027_remove_documento_documento_documento_lido'),
        ('ponto', '0003_ponto_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='ponto',
            name='autor_modificacao',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_autor', to='funcionarios.funcionario', verbose_name='Autor da Modificação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='data_modificacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
