# Generated by Django 5.0.6 on 2025-03-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('funcionarios', '0028_alter_score_options_remove_score_anomes_and_more'),
        ('ponto', '0004_remove_ponto_data_cadastro_ponto_autor_modificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriados',
            name='funcionarios',
        ),
        migrations.RemoveField(
            model_name='feriados',
            name='status',
        ),
        migrations.AddField(
            model_name='feriados',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='feriados',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='feriados',
            name='regiao',
            field=models.CharField(choices=[('NA', 'Nacional'), ('ES', 'Estadual'), ('MU', 'Municipal')], default='NA', max_length=2, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='feriados',
            name='data',
            field=models.DateField(verbose_name='Data Feriado'),
        ),
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0, verbose_name='Pontuação Assiduidade')),
                ('moedas', models.FloatField(default=1, verbose_name='Moedas')),
                ('referencia', models.PositiveIntegerField(editable=False, verbose_name='Referência Ano-Mês')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Fechamentos',
                'verbose_name_plural': 'Fechamentos',
            },
        ),
    ]
