# Generated by Django 5.0.6 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_remove_feriados_funcionarios_remove_feriados_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoabono',
            name='categoria',
            field=models.CharField(choices=[('P', 'Período'), ('T', 'Tempo Faltante')], default='P', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fechamento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoabono',
            name='final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
