# Generated by Django 5.0.6 on 2024-11-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='texto',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('TXT', 'Texto'), ('SLC', 'Seleção'), ('SLM', 'Seleção Múltipla')], default='TXT', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(default='teste', max_length=256, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de Encerramento'),
        ),
        migrations.CreateModel(
            name='TextoPerguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=256, verbose_name='Opção')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Pergunta',
                'verbose_name_plural': 'Opções de Perguntas',
            },
        ),
    ]
